[build-system]
requires = ["setuptools>=68.0.0", "wheel>=0.41.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bajaj-finserv"
version = "1.0.0"
description = "Insurance Policy Document Analysis API"
requires-python = ">=3.8"
